# Load necessary libraries
library(shiny)
library(shinydashboard)
library(ggplot2)
library(dplyr)

# Load the tourism dataset
tourism <- read_csv("data/tourism-gdp-proportion-of-total-gdp.csv")

# Define UI
ui <- dashboardPage(
  dashboardHeader(title = "Tourism GDP Contribution Analysis"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard"))
    )
  ),
  dashboardBody(
    # Custom CSS to style background and panels with a pastel color
    tags$head(
      tags$style(HTML("
        body, .content-wrapper { background-color: #f2f7f7; } /* Light pastel blue */
        .box { background-color: #ffffff; border-radius: 8px; padding: 15px; }
        .box-primary { border-top: 3px solid #007bff; }
        .box-info { border-top: 3px solid #17a2b8; }
      "))
    ),
    tabItems( # Wrapping tabItem inside tabItems
      tabItem(tabName = "dashboard",
              fluidRow(
                # Filter Controls with Explanations
                box(title = "Tourism Data Filters", status = "primary", solidHeader = TRUE, width = 4,
                    p("Select a date range and country to explore the tourism GDP contribution."),
                    selectInput("country", "Select Country:", choices = unique(tourism$Entity)),
                    sliderInput("yearRange", "Select Year Range:",
                                min = min(tourism$Year), max = max(tourism$Year),
                                value = c(min(tourism$Year), max(tourism$Year))),
                    p("The year range selector filters data within specific years for a more tailored analysis."),
                    p("The country selector changes the displayed data, allowing you to focus on tourism’s GDP impact in a specific country.")
                ),

                # Tourism GDP Plot with Explanation
                box(title = "Tourism GDP Contribution Plot", status = "primary", solidHeader = TRUE, width = 8,
                    plotOutput("gdpPlot"),
                    p("The plot illustrates the percentage of GDP generated by tourism over the selected year range.
                    This allows for a closer look at trends and changes over time for the selected country.")
                ),

                # Summary Interpretation
                box(title = "Tourism Data Summary", status = "info", solidHeader = TRUE, width = 12,
                    textOutput("summaryText"),
                    p("Interpretation: This summary provides insights into the general trend of tourism’s GDP contribution over the selected time period.")
                )
              )
      )
    )
  )
)

# Define server logic
server <- function(input, output) {

  # Filtered data based on input
  filtered_data <- reactive({
    tourism %>%
      filter(Entity == input$country,
             Year >= input$yearRange[1],
             Year <= input$yearRange[2])
  })

  # Render Plot
  output$gdpPlot <- renderPlot({
    data <- filtered_data()

    if (nrow(data) == 0) {
      ggplot() +
        labs(title = "No data available for the selected year range.") +
        theme_void()
    } else {
      ggplot(data, aes(x = Year, y = `GDP from tourism as a share of total GDP`)) +
        geom_line(color = "blue", size = 1.2) +
        geom_point(color = "darkblue", size = 2) +
        labs(
          title = paste("Tourism GDP Contribution in", input$country),
          x = "Year",
          y = "Tourism GDP as % of Total GDP"
        ) +
        theme_minimal(base_size = 14) +
        theme(
          plot.title = element_text(face = "bold", size = 16, hjust = 0.5),
          axis.title = element_text(face = "bold"),
          panel.grid.major = element_line(color = "gray80"),
          panel.grid.minor = element_blank()
        ) +
        scale_x_continuous(breaks = seq(min(data$Year), max(data$Year), by = 2)) +
        scale_y_continuous(labels = scales::percent_format())
    }
  })

  # Render Summary Text
  output$summaryText <- renderText({
    data <- filtered_data()
    if (nrow(data) == 0) return("No data available for the selected year range.")

    avg_tourism_gdp <- round(mean(data$`GDP from tourism as a share of total GDP`, na.rm = TRUE), 2)
    max_tourism_gdp <- round(max(data$`GDP from tourism as a share of total GDP`, na.rm = TRUE), 2)
    min_tourism_gdp <- round(min(data$`GDP from tourism as a share of total GDP`, na.rm = TRUE), 2)

    paste("In", input$country, "from", input$yearRange[1], "to", input$yearRange[2],
          "the average tourism GDP contribution was", avg_tourism_gdp, "%, with a maximum of",
          max_tourism_gdp, "% and a minimum of", min_tourism_gdp, "%.")
  })
}

# Run the Shiny app
shinyApp(ui = ui, server = server)























