# Load necessary libraries
library(shiny)
library(shinydashboard)
library(dplyr)
library(ggplot2)

# Define UI for the app with enhanced interactivity and styling
ui <- dashboardPage(
  dashboardHeader(title = "Tourism GDP Analysis"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Explore Data", tabName = "explore", icon = icon("chart-line")),
      menuItem("Download Data", tabName = "download", icon = icon("download"))
    )
  ),
  dashboardBody(
    tabItems(
      # Main data exploration tab
      tabItem(tabName = "explore",
              fluidRow(
                box(width = 4, solidHeader = TRUE, status = "primary",
                    title = "Filters",
                    selectInput("country", "Select a Country:", choices = NULL),  # Choices updated dynamically
                    sliderInput("yearRange", "Select Year Range:",
                                min = 2008, max = 2019, value = c(2008, 2019)),
                    radioButtons("plotType", "Select Plot Type:",
                                 choices = c("Line Plot" = "line", "Bar Plot" = "bar"), inline = TRUE),
                    helpText("Explore the contribution of tourism to the GDP of selected countries over time.")
                ),
                box(width = 8, solidHeader = TRUE, status = "info",
                    title = "Tourism GDP Contribution Over Time",
                    plotOutput("gdpPlot"),
                    br(),
                    h4("Summary Statistics"),
                    verbatimTextOutput("summaryStats")
                )
              ),
              fluidRow(
                box(width = 12, solidHeader = TRUE, status = "success",

                    hr(),
                    h4("Interpretation Guide"),
                    p("The plot shows the percentage of GDP generated by tourism over the selected time range. Higher values indicate a significant role of tourism in the economy, while lower values suggest less reliance on tourism."),
                    p("Trends over time offer insights into how economic conditions or global events affect tourism's role in the economy. Use the selector and slider to explore differences across countries and years.")
                )
              )
      ),

      # Data download tab
      tabItem(tabName = "download",
              fluidRow(
                box(width = 12, solidHeader = TRUE, status = "warning",
                    title = "Download Filtered Data",
                    downloadButton("downloadData", "Download CSV"),
                    p("You can download the filtered data based on your selections for further analysis.")
                )
              )
      )
    )
  )
)

# Define server logic
server <- function(input, output, session) {
  # Dynamically update country choices based on the selected year range
  observe({
    filtered_countries <- tourism %>%
      filter(Year >= input$yearRange[1], Year <= input$yearRange[2]) %>%
      pull(Entity) %>%
      unique()
    updateSelectInput(session, "country", choices = filtered_countries)
  })

  # Reactive data based on country and year range
  filtered_data <- reactive({
    tourism %>%
      filter(Entity == input$country,
             Year >= input$yearRange[1],
             Year <= input$yearRange[2])
  })

  # Summary statistics for the selected country and range
  output$summaryStats <- renderPrint({
    data <- filtered_data()
    if (nrow(data) > 0) {
      stats <- data %>%
        summarize(
          Average = mean(`GDP from tourism as a share of total GDP`, na.rm = TRUE),
          Max = max(`GDP from tourism as a share of total GDP`, na.rm = TRUE),
          Min = min(`GDP from tourism as a share of total GDP`, na.rm = TRUE)
        )
      stats
    } else {
      "No data available for selected filters."
    }
  })

  # Render plot with option to switch between line and bar plot
  output$gdpPlot <- renderPlot({
    plot_data <- filtered_data()
    if (input$plotType == "line") {
      ggplot(plot_data, aes(x = Year, y = `GDP from tourism as a share of total GDP`)) +
        geom_line(color = "#0073C2") +
        geom_point(color = "#0073C2") +
        labs(
          title = paste("Tourism GDP Contribution in", input$country),
          x = "Year",
          y = "Tourism GDP as % of Total GDP"
        ) +
        theme_minimal()
    } else if (input$plotType == "bar") {
      ggplot(plot_data, aes(x = factor(Year), y = `GDP from tourism as a share of total GDP`, fill = factor(Year))) +
        geom_bar(stat = "identity") +
        labs(
          title = paste("Tourism GDP Contribution in", input$country),
          x = "Year",
          y = "Tourism GDP as % of Total GDP"
        ) +
        theme_minimal() +
        theme(legend.position = "none")
    }
  })

  # Download the filtered data
  output$downloadData <- downloadHandler(
    filename = function() {
      paste("tourism_gdp_data_", Sys.Date(), ".csv", sep = "")
    },
    content = function(file) {
      write.csv(filtered_data(), file, row.names = FALSE)
    }
  )
}

# Run the Shiny app
shinyApp(ui = ui, server = server)




























