# Load necessary libraries
library(shiny)
library(dplyr)
library(ggplot2)

# Define the Shiny app UI with added field descriptions and interpretation guide
ui <- fluidPage(
  # Custom CSS styling
  tags$head(
    tags$style(HTML("
            body { background-color: #f0f0f5; } /* Light grey background */
            .well { background-color: #e6f2ff; } /* Light blue panel */
            .titlePanel { color: #003366; font-weight: bold; } /* Dark blue title */
        "))
  ),

  titlePanel("Tourism GDP Contribution Analysis"),

  sidebarLayout(
    sidebarPanel(
      selectInput("country", "Select a Country:",
                  choices = unique(tourism$Entity)),
      sliderInput("yearRange", "Select Year Range:",
                  min = min(tourism$Year),
                  max = max(tourism$Year),
                  value = c(2008, 2019)),
      helpText("This app allows you to explore the contribution of tourism to the GDP of selected countries over time."),

      # Field descriptions
      h4("Field Descriptions:"),
      p("**Entity**: The name of the country."),
      p("**Code**: The standardized country code."),
      p("**Year**: The year in which the data was recorded."),
      p("**GDP from tourism as a share of total GDP**: The percentage of the country's total GDP generated by the tourism sector.")
    ),

    mainPanel(
      plotOutput("gdpPlot"),
      hr(),
      h4("Interpretation Guide"),
      p("The plot shows the percentage of GDP generated by tourism over the selected time range. Higher values indicate a significant role of tourism in the economy, while lower values suggest less reliance on tourism."),
      p("Trends over time offer insights into how economic conditions or global events affect tourism's role in the economy. Use the selector and slider to explore differences across countries and years.")
    )
  )
)

# Define server logic
server <- function(input, output) {
  filtered_data <- reactive({
    tourism %>%
      filter(Entity == input$country,
             Year >= input$yearRange[1],
             Year <= input$yearRange[2])
  })

  output$gdpPlot <- renderPlot({
    ggplot(filtered_data(), aes(x = Year, y = `GDP from tourism as a share of total GDP`)) +
      geom_line(color = "#0073C2") +
      geom_point(color = "#0073C2") +
      labs(
        title = paste("Tourism GDP Contribution in", input$country),
        x = "Year",
        y = "Tourism GDP as % of Total GDP"
      ) +
      theme_minimal() +
      theme(
        panel.background = element_rect(fill = "#F7F9FC"),
        plot.title = element_text(face = "bold", hjust = 0.5)
      )
  })
}

# Run the Shiny app
shinyApp(ui = ui, server = server)


















