#' Tourism GDP Contribution Data
#'
#' The `tourism` dataset contains data on tourism's contribution to GDP across multiple countries and years. This dataset provides insights into how much each country's GDP relies on the tourism sector.
#'
#' @format A data frame with the following columns:
#' \describe{
#'   \item{Entity}{Character. The name of the country.}
#'   \item{Code}{Character. The standardized ISO country code.}
#'   \item{Year}{Integer. The year in which the data was recorded.}
#'   \item{GDP from tourism as a share of total GDP}{Numeric. The percentage of the country's GDP generated by tourism.}
#' }
#'
#' @source World Tourism Organization, International Monetary Fund
#' @examples
#' data(tourism)
#' head(tourism)
