#' Australia Tourism GDP Data
#'
#' The `australia_data` dataset is a subset of the `tourism` dataset, focusing specifically on
#' Australia's tourism GDP contribution over several years. This dataset allows a detailed analysis
#' of tourism's impact on Australia's economy.
#'
#' @format A data frame with the following columns:
#' \describe{
#'   \item{Entity}{Character. Country name, fixed as "Australia" for this dataset.}
#'   \item{Code}{Character. Country code, fixed as "AUS" for Australia.}
#'   \item{Year}{Integer. The year in which the data was recorded (e.g., 2008, 2019).}
#'   \item{GDP from tourism as a share of total GDP}{Numeric. The percentage of Australia's total GDP that is generated by tourism (e.g., 3.5).}
#' }
