
## 1. Main Function Documentation (runMyShinyApp)

#' Launch the EcoTourImpact Shiny App
#'
#' The `runMyShinyApp` function launches an interactive Shiny app that enables users to explore the tourism GDP contribution across various countries and years. Users can filter by country, adjust the year range, choose between different plot types, and view summary statistics.
#'
#' @return A Shiny app interface allowing users to interactively explore tourism GDP data.
#' @examples
#' if (interactive()) {
#'   runMyShinyApp()
#' }
#' @export
runMyShinyApp <- function() {
  shinyApp(ui = ui, server = server)
}

## 2. Data Documentation (tourism Dataset)

Document the tourism dataset using roxygen2. This documentation should explain each column and provide an example of how to load the data.

#' Tourism GDP Contribution Data
#'
#' The `tourism` dataset contains data on tourism's contribution to GDP across multiple countries and years. This dataset provides insights into how much each country's GDP relies on the tourism sector.
#'
#' @format A data frame with the following columns:
#' \describe{
#'   \item{Entity}{Character. The name of the country.}
#'   \item{Code}{Character. The standardized ISO country code.}
#'   \item{Year}{Integer. The year in which the data was recorded.}
#'   \item{GDP from tourism as a share of total GDP}{Numeric. The percentage of the country's GDP generated by tourism.}
#' }
#'
#' @source World Tourism Organization, International Monetary Fund
#' @examples
#' data(tourism)
#' head(tourism)
#'
#' # Example of filtering data for a specific country
#' library(dplyr)
#' australia_data <- tourism %>% filter(Entity == "Australia")
"tourism"

## 3. Helper Functions Documentation

#' Filter Tourism GDP Data by Country and Year Range
#'
#' This function filters the tourism GDP dataset based on a specified country and year range. It is useful for extracting a subset of the data for detailed analysis or visualization.
#'
#' @param data The tourism dataset.
#' @param country Character. The name of the country to filter by.
#' @param year_range Numeric vector of length 2. The start and end year for filtering.
#' @return A data frame containing the filtered tourism data.
#' @examples
#' data(tourism)
#' filtered_data <- filter_tourism_data(tourism, "Australia", c(2008, 2020))
#' head(filtered_data)
#' @export
filter_tourism_data <- function(data, country, year_range) {
  data %>%
    filter(Entity == country,
           Year >= year_range[1],
           Year <= year_range[2])
}

#' Plot Tourism GDP Contribution Over Time
#'
#' This function generates a plot of tourism's contribution to GDP for a given country over time. Users can specify the data to be plotted, allowing for customized visualizations.
#'
#' @param data A data frame containing the filtered tourism GDP data.
#' @return A ggplot2 object that displays the tourism GDP contribution over time.
#' @examples
#' data(tourism)
#' australia_data <- filter_tourism_data(tourism, "Australia", c(2008, 2020))
#' plot_tourism_gdp(australia_data)
#' @export
plot_tourism_gdp <- function(data) {
  ggplot(data, aes(x = Year, y = `GDP from tourism as a share of total GDP`)) +
    geom_line(color = "#0073C2") +
    geom_point(color = "#0073C2") +
    labs(
      title = paste("Tourism GDP Contribution in", unique(data$Entity)),
      x = "Year",
      y = "Tourism GDP as % of Total GDP"
    ) +
    theme_minimal()
}


## 4. Summary Statistics Function

#' Summarize Tourism GDP Contribution Statistics
#'
#' This function calculates summary statistics (average, maximum, minimum) for tourism GDP contribution over a specified dataset. Useful for understanding the range and central tendency of tourism's economic impact.
#'
#' @param data A data frame containing the filtered tourism GDP data.
#' @return A data frame containing the average, maximum, and minimum tourism GDP values for the specified country and year range.
#' @examples
#' data(tourism)
#' australia_data <- filter_tourism_data(tourism, "Australia", c(2008, 2020))
#' summarize_tourism_stats(australia_data)
#' @export
summarize_tourism_stats <- function(data) {
  data %>%
    summarize(
      Average = mean(`GDP from tourism as a share of total GDP`, na.rm = TRUE),
      Max = max(`GDP from tourism as a share of total GDP`, na.rm = TRUE),
      Min = min(`GDP from tourism as a share of total GDP`, na.rm = TRUE)
    )
}




